excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://thorstenweber83.github.io
title: tinywatch
tagline: bootswatch tinypress theme
description: Just usin' some styles
paginate: 5
