excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://thorstenweber83.github.io
title: main title
tagline: bootswatch tinypress theme
description: a short descrption
paginate: 5
