excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://thorstenweber83.github.io
title: thorstenweber83
tagline: A log of everyday life
description: My awesome new site
paginate: 5
